image: gitpod/workspace-full

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true

# Each '-' under 'tasks' corresponds to a separete terminal
tasks:
  # Runs only when a workflow is started
  - init: bundle install